services:
  db:
    image: 'mysql:8.0.37'
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PWD}
    ports:
      - "3306:3306"
    volumes:
      - db-store:/var/lib/mysql
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]

volumes:
  db-store: