services:
  db:
    image: 'mysql:8.0.37'
    environment:
      MYSQL_DATABASE: "gitpulse"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "rootpassword"
    ports:
      - "3306:3306"
    volumes:
      - db-store:/var/lib/mysql
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]